### ISSUE TITLE
書き込みにシングルクォートがあるとdb接続エラーになる

### ISSUE THREAD

**Issue by satopian** [sakots/ROIS#10]
SQLのためのエスケープが無い?

> i'm looking for t-shirt.

はdb接続エラーになります。

**Comment by sakots** [comment]
あ、入力時のHTMLエスケープ撤廃のときに一緒に外れてしまいました

**Comment by sakots** [comment]
たぶんダブルクォートもエラーになります

**Comment by sakots** [comment]
現在対処中。
また、データベース名も設定できるように変更中

**Comment by sakots** [comment]
対処法を探しに探した結果、かなり原始的対応をしました…

**Comment by sakots** [comment]
OK
