### ISSUE TITLE
クッキー

### ISSUE THREAD

**Issue by satopian** [sakots/ROIS#12]
`$cooks = array("namec<>".$names,"emailc<>".$mail,"urlc<>".$url);`
`<>`をエスケープ文字にしない時は、区切り文字に`<>`を使うべきではないと思います。(意図しない区切りになって誤動作する)
`"\t"`タブ区切り文字が適当ではないでしょうか?
そのタブ文字も誤動作を避けるため置換して削除しておいたほうがいいと思います。
使ったツールやキャンバスサイズもクッキーにセットすれば、
loadcookie.jsを少し変更するだけでクッキーをセットできるのでユーザーにとって使いやすい掲示板になると思います。

**Comment by sakots** [comment]
ですね
通常のCSVかjson形式にしようと思います。

**Comment by satopian** [comment]
jsonはよくわかりませんが、
この箇所は
```
			$cooks = array("namec<>".$names,"emailc<>".$mail,"urlc<>".$url);

			foreach ( $cooks as $cook ) {
				list($c_name,$c_cookie) = explode('<>',$cook);
				// $c_cookie = str_replace("&amp;", "&", $c_cookie);
				setcookie ($c_name, $c_cookie,time()+(SAVE_COOKIE*24*3600));
			}

```
配列のループで、さらにそこから2つの値を配列にするための区切り文字が`<>`というだけなので、
ループ処理をしないで一つづつ
`			setcookie ("pwdc", $c_pass,time()+(SAVE_COOKIE*24*3600));
`
とすればこの問題は回避できると思います。
また、同じにする必要はありませんが
```
	//クッキー項目："クッキー名 クッキー値"
	$cooks = ["namec\t".$name,"emailc\t".$email,"urlc\t".$url,"fcolorc\t".$fcolor,"pwdc\t".$c_pass];

	foreach ( $cooks as $cook ) {
		list($c_name,$c_cookie) = explode("\t",$cook);
		setcookie ($c_name, $c_cookie,time()+(SAVE_COOKIE*24*3600));
	}

```
EVOはタブ区切り文字です。

**Comment by sakots** [comment]
OK
