### ISSUE TITLE
global変数

### ISSUE THREAD

**Issue by satopian** [sakots/ROIS#13]
[これを便利ととるか、危険ととるかはエンジニア次第ですが、非常に大きな問題です。  例えばglobalキーワードの後で$name = &quot;コロ&quot;;と、変数の中身を上書きしていますので、グローバル変数が上書きされます。](https://qumeru.com/magazine/589)
```
/* 記事書き込み */
function regist() {
	global $name,$com,$sub,$parent,$picfile,$img_w,$img_h,$mail,$url,$time,$pwd,$pwdh,$exid,$invz;

```
引数で渡す代わりに、global宣言していますが、よく見る一般論では、便利かもしれないけれど危ないかもしれないとなっています。
別の関数にも影響がでるからです。
最後にアンセット
unset($name,$mail,$sub,$com,$url,$pwd,$pwdh,$resto,$pictmp,$picfile,$mode);
が入っているのはそのあたりの意図なのかもしれませんが、returnしなくても、書き換わった変数が別の関数の中に入るかもしれないという事なので、あまりよくない書き方なのではないでしょうか?
これがあるからバグが出るという証明ができるわけではないのですが…。
行数が長くなりますが、
$name,$mail,$sub,$com,$url,$pwd,$pwdh,$resto,$pictmp,$picfile,$mode
などの外部からPOSTされる変数は、関数内で取得するか、でなければ関数の引数で渡したほうが安全だと思います。
globalにしなければならない変数は、例えばconfig.phpで設定した変数で、こればかりは何度もrequireするわけにはいかないので仕方がないと思います。

**Comment by sakots** [comment]
ですね

**Comment by sakots** [comment]
OK
