### ISSUE TITLE
幅と高さとツールとパレットをCookieに保存してロード

### ISSUE THREAD

**Issue by satopian** [sakots/ROIS#14]
[幅、高さ、アプリの種類のCookieをロード。 · satopian/ROIS@7d6afda](https://github.com/satopian/ROIS/commit/7d6afda150aa5e7d56c35c0b63a3d32cffd6cf35)
[幅、高さ、アプリの種類をCookieに保存。 · satopian/ROIS@266376e](https://github.com/satopian/ROIS/commit/266376eb255321c0172717b78426bb23c58491bc)
パレットのCookieもPHPでと思いましたが、themeのほうでループしていたでここには入っていません。
やるとしたら、そこだけJavaScriptで書く感じでしょうか?

**Comment by satopian** [comment]
hiddenにCookieのキャンバスサイズが入るので、続きから描く時の画像の幅高さを再取得。 · satopian/ROIS@e722864
https://github.com/satopian/ROIS/commit/e7228642ee0d154a8da362ae574b196699c04926

**Comment by satopian** [comment]
`$sql = "SELECT * FROM tablelog WHERE picfile='$no' ORDER BY tree DESC";`
とした箇所はとりあえず動かすために変更したものなので、正しい処置なのかどうかわかりません。
さこつさんのほうで再検証してください。

**Comment by sakots** [comment]
パレットのCookieは、selectのoptionにidふってやれば同じ処理でできそう

**Comment by sakots** [comment]
高さと幅とアプリの種類をCookieに保存するかはconfigで設定したいなあ（俺は描くときにこれを考えるのが楽しいので）
その他取り込みました。

**Comment by satopian** [comment]
別に最初にSELECTされるプルダウンメニューが決まるだけで、そこから自由に選択できますので、
毎回考えるとCookieで保存は普通に両立できると思いますが…。

**Comment by satopian** [comment]
必要ないみたいですが…。
paletteのCookie対応版です。
paletteのCookie対応。 · satopian/ROIS@552d53b
https://github.com/satopian/ROIS/commit/552d53bee97879a48c8c55ea7d9591fc3bf45e54
気が変わった時にでも…。

**Comment by sakots** [comment]
パレットは好みがあるので必要です。

> 最初にSELECTされるプルダウンメニューが決まる

つまり使いたいツールを選ぶ「手間」がなくなってしまっているわけで、いわゆる脳死が発生します。

**Comment by sakots** [comment]
パレットの選択はストレスになるのに対し、ツールの選択は楽しみの減少と捉えます。

**Comment by satopian** [comment]
個人的には、POTI-boardやほかのお絵かき掲示板じゃなくてROISを使いたいと思う人が潜在的に少なくなってしまいそうな点が残念です。
POTI-boardと同じでなければならないというわけではありませんが、例えばChickenPaintでいつも描く人は、NEO、しぃぺ、ChickenPaintと選択しなければならず、NEOの人はボタンを押すだけがCookieなしの状態。
Cookieがセットされていれば、前回使ったツールがでてきて、別のツールを使いたかったら切り替え。
この場合、NEOはデフォルトで描けますなので、自分が使いたいツールはChickenPaintなんだけどという人にだけ手間をかけさせることにもなります。
設計思想の違いという事なら
こちらでフォークしたリポジトリを育てるかも…。
というか、POTIが潰れても絵板は残る、使いたいという人がたくさん出てくるを期待してはいるのですが、これもなんのために開発しているのかの思想の相違なら仕方ないです。

**Comment by sakots** [comment]
「できればNEOを使って欲しい」というのはあります
