### ISSUE TITLE
続きを描くでdb接続エラーになる

### ISSUE THREAD

**Issue by satopian** [sakots/ROIS#15]
タイトルの通りです。続きを描く事ができません。

**Comment by satopian** [comment]
幅、高さ、アプリの種類のCookieをロード。 · satopian/ROIS@7d6afda
https://github.com/satopian/ROIS/commit/7d6afda150aa5e7d56c35c0b63a3d32cffd6cf35
```
		$db = new PDO("sqlite:rois.db");
		$sql = "SELECT * FROM tablelog WHERE picfile='$no' ORDER BY tree DESC";
```
`'$no'`をシングルクォートで囲えばエラーはでなくなりますが、それが正しい処置かどうかはわかりません。

**Comment by sakots** [comment]
ただしいです

**Comment by sakots** [comment]
なおしました
