### ISSUE TITLE
お絵かき画面の色

### ISSUE THREAD

**Issue by satopian** [sakots/ROIS#17]
![image](https://user-images.githubusercontent.com/44894014/129479817-89a864a8-26ed-4824-b807-f278dc19b8d9.png)
作画するときに、周囲の色にひっぱられて色塗りがうまくできないと感じる人もいるようです。
クリスタや、CorelPainterもダーク系を採用してアプリの色をあまり主張しなくなりました。
Painterは、それをイラストが主役になる配色といって宣伝していますし、Photoshopも、ほかのPaintアプリもおおよそ同じ設計思想で配色を決めているようです。
さこつさんはどう思いますか?

**Comment by sakots** [comment]
たしかにそうですね。彩度を抑えてみます。

**Comment by sakots** [comment]
POTIのMONODEVのほうにも適用します。

**Comment by sakots** [comment]
![image](https://user-images.githubusercontent.com/31465648/129480983-a6cd26e4-05b9-43fa-9ad4-d2c78eb29000.png)
このくらいでどうでしょうか

**Comment by satopian** [comment]
POTIの同梱テーマはこちらでもやりましたが、これならキャンバスの色は淡いグレーですから特に問題ないと思います。

**Comment by sakots** [comment]
ありがとうございます。

**Comment by satopian** [comment]
![image](https://user-images.githubusercontent.com/44894014/129481513-6f3f61eb-c64a-44d9-ad20-d4f7087c6f4d.png)
貼ってもいいか迷いましたが、mayoの配色の変更後。
少し元の色を残さないと全体のバランスがとれないからという理由からこのあたりの配色になっています。

**Comment by sakots** [comment]
私はこうしてみました。
![image](https://user-images.githubusercontent.com/31465648/129481635-d6d58191-f17d-4966-88f7-21042a78e73d.png)
罫線の色の方にアクセントを残しています。

**Comment by satopian** [comment]
こっちのほうがいいですね。

**Comment by sakots** [comment]
とりあえず現状更新はしましたので閉じます。
