### ISSUE TITLE
toolのユーザーデータファイルへの書き込みの時のタブ区切りの順序

### ISSUE THREAD

**Issue by satopian** [sakots/ROIS#20]
`$userdata .= "\t$usercode\t$repcode\t$stime\t$time\t$resto"; `これまで
↓
`$userdata .= "\t$usercode\t$repcode\t$tool\t$stime\t$time\t$resto";` 現在

この場合、タブ区切りで情報を取り出す時に、
**これまで描画開始時間だったところにツールが入る**事になります。
このpicpost.phpは最新バージョンのROISのためだけのものならそれでもいいのですが、
互換性を重視するなら
ツール情報は末尾に追加のほうがいいのではないでしょうか?
タブ区切りで取り出す情報は同じになり、末尾にツールが追加されます。

`$userdata .= "\t$usercode\t$repcode\t$stime\t$time\t$resto"; ` これまで
↓
`$userdata .= "\t$usercode\t$repcode\t$stime\t$time\t$resto\t$tool";` 並び順は同じで、末尾にツール。
index.phpで取り出す時の並び方も変更しなければいけませんが、picpost.phpのバージョンがあわなくても誤動作にはいたりません。

今回変更されたタブ区切りの順序はPOTIーboardとの非互換となるため、間違ってこの`picpost.php`や`save.php`を使うと、描画時間の記録やレス先の記録が正しく行われません。

末尾にツールが追加されていれば、ROISの古いバージョン、POTI-boardでも誤動作しません。
さこつさんの意見を聞かせてください。

**Comment by sakots** [comment]
たしかにそうなのですが、末尾に組み込む方法がわかりませんでした。

**Comment by satopian** [comment]
ついでに見つけてしまいましたが、続きを描くを使うとバグりますね。
explode()で、タブ区切りになっているので、並び方が変わった事でさこつさんが意図したものではないものが入ってしまっています。

`			list($uip,$uhost,$uagent,$imgext,$ucode,$urepcode,$starttime,$postedtime) = explode("\t", rtrim($userdata)."\t");//区切りの"\t"を行末にして配列へ格納
`
末尾への組み込み方法。
動作確認はしていませんが。

`picpost.php`と、`save.php`
`$userdata .= "\t$usercode\t$repcode\t$stime\t$time\t$resto\t$tool";`

`index.php`
`index.php`側
//画像差し換え用
`list($uip,$uhost,$uagent,$imgext,$ucode,$urepcode,$starttime,$postedtime,,$tool) = explode("\t", rtrim($userdata)."\t");`
//新規投稿用
`list($uip,$uhost,$uagent,$imgext,$ucode,,$starttime,$postedtime,,$tool) = explode("\t", rtrim($userdata)."\t");`

**Comment by sakots** [comment]
ありがとうございます。クッキーに正しくパスワードが保存されないものこれかなあ…

**Comment by sakots** [comment]
なおったはず
