### ISSUE TITLE
セキュリティ

### ISSUE THREAD

**Issue by satopian** [sakots/ROIS#5]
```
//スパム無効化関数
function newstring($string) {
	$string = htmlspecialchars($string,ENT_QUOTES,'utf-8');
	$string = str_replace(",","，",$string);
	return $string;
}
//無効化ここまで
```
PHP４時代には、入力時にエスケープすれば良いと考えられていましたが、入力時のチェックをもって｢スパム無効化｣とするのは、セキュリティ対策ではないという考え方が主流になっています。

>[1-2. クロスサイトスクリプティング](https://www.ipa.go.jp/security/awareness/vendor/programmingv1/a01_02.html)
> サニタイジングのタイミングはHTML生成時
> クロスサイトスクリプティングの解説記事でよく説明される「入力データチェックを厳密に」という表現から，図3の(1)フォーム受付時のタイミングでサニタイジングを行うのかと思いがちである。サニタイジングは(2)HTML生成時のタイミングで行うべきである。

> [サニタイズ/入力値検証/エスケープの考え方 - Qiita](https://qiita.com/rana_kualu/items/11cd41de5f0364ba2ee8)
> 入力値検証はセキュリティ対策ではない
> サニタイズ > ( 入力値検証 + エスケープ )
> ・入力値検証とエスケープの区別ができていれば、そうそう脆弱性は入らない

> [htmlspecialcharsはHTML出力用エスケープであってSQL出力用エスケープではない。](https://qiita.com/sonsyu0103/items/352505db0bfb8dbe1611)

Bladeを使って出力しているので、出力時にエスケープが入ります。
しかし、
`{!!$bbsline['com']!!}`
となっている箇所はテンプレートエンジンではエスケープされません。
試しに、入力時のエスケープを外してみます。
`$com = filter_input(INPUT_POST, 'com');`
するとdbにはいっているHTML、JavaScriptがそのまま出力されてしまいます。
コメント欄の`<br>`やurlのオートリンクによるタグがあるから、Blade側でエスケープできない問題は、
`<br>`は一度`\n`に戻す。
オートリンクによってタグが追加される直前で、`htmlspecialchars($string,ENT_QUOTES,'utf-8',false);`によってエスケープすれば出力時のコメントのエスケープも可能です。
POTI-boardは、入力時にエスケープしたログファイルが存在していて、さらにエスケープされていないログファイルもあるので、投稿者がタグ有効を前提に投稿したものは、タグを除去してさらにエスケープ。
すでにエスケープされているものは、二重エンコードをしない設定にしてエスケープする事で対応しました。
これは、古いアプリだからであって、新しいアプリでは入力時の`htmlspecialchars`をやめて、
出力に対してだけ、`htmlspecialchars`または`htmlentities`を使ったほうがいいのではないでしょうか?
入力時の`htmlspecialchars`は文字化けが起きるだけでセキュアではないというQiitaの記事もありました。
出力時のエスケープはBladeであれば比較的容易で
`{!!$bbsline['com']!!}`のように、!!を入れてテンプレートエンジンによるエスケープが入るのを回避している箇所以外は、`htmlentities`によってエスケープされますから、あとは、それに加えて
`{!!$bbsline['com']!!}`にあたる箇所に出力時の`htmlspecialchars`をかける。
QiitaとIPAの記事を少し読んだだけですが、セキュリティに関する箇所の私の理解はだいたいこんな感じです。

**Comment by sakots** [comment]
ありがとうございます。

**Comment by sakots** [comment]
やはり「データベースのサイズをあとから変えるのが一般的には難しい」ということで、イチから作りなおす方向にしました。

**Comment by sakots** [comment]
とりあえずこれはひとまず対処します。

**Comment by sakots** [comment]
https://github.com/sakots/ROIS/releases/tag/v0.3.0

対応できました。ありがとうございます。
