### ISSUE TITLE
拡張ヘッダ

### ISSUE THREAD

**Issue by satopian** [sakots/ROIS#6]
```
			//なぜかうごかないので
			//list($uip,$uhost,$uagent,$imgext,$ucode,$urepcode,$starttime,$postedtime) = explode("\t", rtrim($userdata)."\t");//区切りの"\t"を行末に

```
の箇所ですが、

続きから描くの画面の時に
`<param name="send_header" value="usercode=hoge">`
になっていて、usercodeしかはいっていないので、
picpost.phpの
```
/* ---------- 投稿者情報記録 ---------- */
$userdata = "$u_ip\t$u_host\t$u_agent\t$imgext";
// 拡張ヘッダーを取り出す
$sendheader = substr($buffer, 1 + 8, $headerLength);
if($sendheader){
	$sendheader = str_replace("&amp;", "&", $sendheader);
	$query_str = explode("&", $sendheader);
	foreach($query_str as $query_s){
		list($name,$value) = explode("=", $query_s);
		$u[$name] = $value;
	}
	$usercode = isset($u['usercode']) ? $u['usercode'] : '';
	$repcode = isset($u['repcode']) ? $u['repcode'] : '';
	$stime = isset($u['stime']) ? $u['stime'] : '';
	$resto = isset($u['resto']) ? $u['resto'] : '';
	//usercode 差し換え認識コード 描画開始 完了時間 レス先 を追加
	$userdata .= "\t$usercode\t$repcode\t$stime\t$time\t$resto";
}

```
のこの箇所で、$usercodeしか取得できていません。
取得できていれば、未投稿画像のテンポラリに入っている拡張子`.dat`のフィアルをひらくとタブ区切り形式で拡張ヘッダの情報の確認ができます。
開発者が必要な情報を適当に考えて追加していいですよとしぃちゃんが開放したのが拡張ヘッダなので好きな情報を追加できます。

`<param name="send_header" value="usercode=fuga&stime=1628000000&repcode=hoge">
`のようになります。
レスならレスに関する情報も入ります。
こうする事ですぐに投稿しないで未投稿画像になった時にも、レス先や描画開始時間と終了時間が記録されているので、未投稿から投稿した時にも情報が保持されます。
&をエスケープするべきだはChickenPaintではエスケープすると動作しなかったので、実際にurlにパラメータとして使う時の&はエスケープしないで使ってます->POTIでは。
意見が違う箇所もあるかとは思いますが、拡張ヘッダに情報を書くと、picpost.phpで受信して情報ファイルに書き込む事ができますという事です。
出典は20年近く前のしぃちゃんのドキュメントになります。

**Comment by sakots** [comment]
なるほど。ありがとうございます。
ChickenPaintではエスケープすると動作しなかったのは確認しましたが、これはjson形式の配列の中身だからかと思います。

**Comment by satopian** [comment]
いえ、$_GETのための? &の動作の問題でした。ChickenPaint。
picpostは、内部で`&amp;`を`&`に戻しているから動くみたいですね。
`	$sendheader = str_replace("&amp;", "&", $sendheader);
`

**Comment by sakots** [comment]
ああ、URLとして処理されているものだと思ってたんですが、そこが間違ってたんですね。
ありがとうございます。

**Comment by satopian** [comment]
`$var_b += array('usercode'=>$usercode);
`
ユーザーコードに、文字通りのユーザーコードをセット。

そのユーザーコードにいろいろ足す。

```
$usercode.='&amp;stime='.time();//拡張ヘッダに描画開始時間をセット

//差し換え時の認識コード追加
if($type === 'rep'){
	$no = filter_input(INPUT_POST, 'no',FILTER_VALIDATE_INT);
	$userip = get_uip();
	$time=time();
	$repcode = substr(crypt(md5($no.$userip.$pwdf.date("Ymd", $time)),$time),-8);
	//念の為にエスケープ文字があればアルファベットに変換
	$repcode = strtr($repcode,"!\"#$%&'()+,/:;<=>?@[\\]^`/{|}~","ABCDEFGHIJKLMNOabcdefghijklmn");
	$datmode = 'picrep&amp;no='.$no.'&amp;pwd='.$pwdf.'&amp;repcode='.$repcode;
	$usercode.='&amp;repcode='.$repcode;
}

```
`$var_b += array('usercode'=>$usercode); //usercodeにいろいろくっついたものをまとめて出力
`
+による配列の結合を行っているので、すでにキーが存在している配列はあとから+した値で上書きされない。
ここでは元のユーザーコードのみがはいったものになる。
[プラス演算子は配列1の後ろに配列2が結合されるのではなく、配列のキーが重複していた場合は、先の配列のキーが優先されます。](https://www.sejuku.net/blog/28533)

```
	// $var_b += array('usercode'=>$usercode); //usercodeにいろいろくっついたものをまとめて出力(されない
	$var_b = array_merge($var_b,['usercode'=>$usercode]);//このコードではいろいろはいります。

```
↑
テストの結果うまくいったもの。
同じキーの配列の値を上書きする時はarray_merge()。
+では、上書き(再代入)されない。

**Comment by satopian** [comment]
上のコメントを無視したのではなくて、書いているうちにさこつさんのレスが入っていたようです…。
```
	$usercode = (string)filter_input(INPUT_GET, 'usercode');
	$repcode = (string)filter_input(INPUT_GET, 'repcode');
	$stime = (string)filter_input(INPUT_GET, 'stime');
	$resto = (string)filter_input(INPUT_GET, 'resto');

```
ChickenPaintには拡張ヘッダがないので、その代わりにgetで必要な情報をsave.phpに渡していますがエスケープした`&`では受信できなかったので、エスケープをやめました。

**Comment by sakots** [comment]
ありがとうございます。

**Comment by satopian** [comment]
作業中かもしれないので、確認をとってからにしますけど、
プラス演算子で配列を足すのをやめて、POTI-boardとまったく同じ形式に書き直す処理をさっきこちらでやりました。
簡単な動作確認をした限りでは問題なく動作します。
これ、プルリクしてもいいですか?
```
	$var_b ['picw'] = $picw;
	$var_b ['pich'] = $pich;
	$var_b ['w'] = $w;
	$var_b ['h'] = $h;
	$var_b ['pchfile'] = './'.$pch;
	$var_b ['datasize'] = $datasize;

	$var_b ['speed'] = PCH_SPEED;

	$var_b ['path'] = IMG_DIR;
	$var_b ['a_stime'] = time();

	echo $blade->run(ANIMEFILE,$var_b);

```
形式としてはこう。
正規表現の一括置換なので、置換しきれていない箇所もあるかもしれせんが、再代入している箇所は意図通りの動作になるかもしれません。

**Comment by satopian** [comment]
そうですね。プルリクするだけして、いらなかったら捨ててください…。
どんなコードなのか見ないと判断できないかもしれませんし。

**Comment by sakots** [comment]
お願いします。というかそれ動くのか…！

**Comment by satopian** [comment]
プルリクしました。
こちらで確認した限りでは拡張ヘッダも入ったので、こっちのほうが予期しないバグが発生しにくいと思います。

**Comment by satopian** [comment]
それが動くから、BladeはPOTIのテンプレートエンジンの代替候補なんです。
本体の書き換えとHTMLの書き換え同時はきついので。

**Comment by satopian** [comment]
`(\$var_b )\+= (array)\(('.+')=>(.+)\);`
↓
`$1[$3] = $4;`
変換に使った正規表現。

**Comment by satopian** [comment]
画像差替の処理の修正と、続きから描いた時の描画時間が、描いた時刻から、続きを描いた時刻までの合計になっていて、たとえば1秒描いて、1日放置してまた1秒描くと描画時間が｢1日2秒｣になっていたのを修正してみましたが、そちらでも作業しているようならプルリクしませんし、必要ならプルリクします。
プルリクしないまでも、こちらのリポジトリにコードを仮にあげる事もできますが、どうしましょうか。

**Comment by satopian** [comment]
https://github.com/satopian/ROIS
あげるだけあげておきました。
mergeされないようなら、ここのリポジトリと同期を取らないといけないのであとで消します。

**Comment by sakots** [comment]
マージしました。
