### ISSUE TITLE
続きから描いた画像のファイル名が同じなのでキャッシュが表示される

### ISSUE THREAD

**Issue by satopian** [sakots/ROIS#8]
続きから描いた画像がファイル名が同じなので更新されません。
さらにChickenPaintの場合は、続きから描く時に、chiフィアルや画像ファイルのキャッシュをキャンバスに読み込んでしまう事があるので、数時間分の作業が反映されず作業に支障がでる事があります。
可能であれば、POTI-boardのように、続きから描いたファイルには続きから描いたユニックスタイムを再度入れたほうがいいと思うのですが、どうでしょうか?
dbがらみの箇所だったのでこちらではいじりませんでした。

**Comment by sakots** [comment]
実はいつのtime()で命名されているのかが不明で、名称変更はしていませんでした。
そこさえ確定すれば、解決できます。

**Comment by sakots** [comment]
拡張ヘッダに正しい時刻が入ったことで、特定できました。
これから作業します。

**Comment by satopian** [comment]
`$filename=time().$time.substr(microtime(),2,3);`
こんな感じです。
このscriptは、picpostのfile名のままなんですね。
でも、それならそれで、続きを描く時にも元のファイル名を使うのではなくて、Paint処理と同じようにテンポラリのファイル名を使うでもいいと思います。
別途上記のファイル名を使っても同じ事ですが…。
拡張ヘッダの時刻は描画開始時刻なので、テンポラリのファイル名を使ったほうが一貫性があるかもしれません。

**Comment by satopian** [comment]
あと、描画開始時刻のヘッダは10桁のユニックスタイムで、ファイル名は13桁ですから、拡張ヘッダの時間は仕様から考えると使えないです。

**Comment by sakots** [comment]
テンポラリで行きますかねー

**Comment by satopian** [comment]
たぶん
`TEMP_DIR.$file_name.$imgext`
の
`$file_name`

**Comment by sakots** [comment]
ですね！

**Comment by sakots** [comment]
修正完了したのでこれからGithubに上げます

**Comment by sakots** [comment]
かいけつ！
