### ISSUE TITLE
ChickenPaintのchiファイルがあると、動画リンクが出る

### ISSUE THREAD

**Issue by satopian** [sakots/ROIS#9]
https://github.com/satopian/ROIS/commit/5d7247761e5e99e03faccb63a45e1602ff2b1595
作業中かもしれないのでプルリクはしませんが、修正してみたものをリポジトリにプッシュしておきました。

**Comment by satopian** [comment]
https://github.com/satopian/ROIS/commit/852c9eb625b490fcae3c87a8dc6e85449d02a8ae
これも、作業中かもしれないので、リポジトリにプッシュだけしておきました。
パレットのファイルの変数が未定義になっていました。

**Comment by satopian** [comment]
ゆるやかな比較で true と比較する意味が無い箇所を整理。 · satopian/ROIS@15b16d1
https://github.com/satopian/ROIS/commit/15b16d191e7295ec7639880236a2b2e5d1242691
マージされない場合は、同期を取る必要があるのであとで消します。

**Comment by satopian** [comment]
ディスカッションがあれば、そっちに書きますが、
templateの変数の分岐が今の形でエラーを出す事なくできているのはすごい、と思います。
いつかBladeを使ったPHPを書く時の参考にさせていただきます。
もっと、変数は定義済みかどうか厳しくチェックしないとエラーが出るものだと思っていました。
XAMPPのエラーログも観ていますので、本当にエラーがでてない感じです。

**Comment by satopian** [comment]
本題の動画のリンクが出るが直っていなかったので調べてみたところ、NEOの動画なし、ChickenPaintレイヤーなしどちらも動画リンクがでていました。
`@if (isset($bbsline['pchfile']))`という判定では、`''`でも定義ずみなので動画のリンクが出てしまう。 · satopian/ROIS@4a5300b
https://github.com/satopian/ROIS/commit/4a5300b5a2d9653b982be20d33bf4e850439a801
修正が必要な箇所。
`@if (isset($bbsline['pchfile']))`
だと、定義されている変数かどうかしかみていないため、ブランク(空白)でも、定義ずみになってtrueになります。
`@if ($bbsline['pchfile'])`
とすれば、動画のリンクを出す出さないを判定できました。
また、この書き方でも未定義のエラーは出ないようです。
作業中だと思いますのでプルリクはしません。

**Comment by sakots** [comment]
> 変数は定義済みかどうか厳しくチェックしないとエラーが出るものだと思っていました。

Bladeがそのへんのクッションをやってる感じですね。
`@if ($bbsline['pchfile'])`で行きますが、`@if (!empty($bbsline['pchfile']))`も試してみます。

**Comment by sakots** [comment]
なお、今の所「サーバーからは配列だけ返して、レンダリングはjavascript（ユーザーサイド）で行う」がベターだと思ってまして、VueとかReactとかを勉強しております

**Comment by satopian** [comment]
POTIはいい加減なところがあるので、未定義のままの変数をdefでfalseにしちゃってます。
さこつさんのROISの動画リンクのところは、動画があってもなくても、少なくともブランクが入っているようです。
ブランクならfalseでいいのなら、単純に
`@if ($bbsline['pchfile'])`
ブランクすら入らない未定義変数の可能性があるなら
`if (!empty($bbsline['pchfile']))`
XAMPPのサーバエラーログをVScodeに表示してチェックしていますが、エラーが何も表示されないので、
`@if ($bbsline['pchfile'])`
でいいと思うんです。

**Comment by sakots** [comment]
ありがとうございます。

**Comment by sakots** [comment]
noe/ROISは、POTIからさとぴあさんが修正/追加した機能以外はすべてイチから書いてます。2020年ですからね。
POTIができた当時はPHPが3とか4とかの時代でしたから、PHPもいい加減でしたし。

**Comment by satopian** [comment]
> 「サーバーからは配列だけ返して、レンダリングはjavascript（ユーザーサイド）で行う」がベター

その技術を知らないので間違っているかもしれませんが
今はスマホに対応できないものは、ほぼ使い物にならなくなっている時代なのでユーザーの端末に負荷をかけるものはうまくいかない気がします…。
ページの処理が重くてなかなか応答がかえってこない→グーグルの検索ランクが下がる説もありますし、
[PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?hl=ja)
↑
ここでは、不要なJavaScriptを削れといつもでてきます。それはグーグルアナリティクスのJSなのに…となりますね。
それから、外部化されたCSSとJSは表示速度を落とすのでメンテナンスは大変になるけれどインライン化すべきともいわれています。
速度が落ちるだけで来る人の数が減ると言われているので、私はそれを回避しますね。

**Comment by satopian** [comment]
> すべてイチから

futaba.phpのコードは入ってないと思いますが、POTI-boardのお絵かき関連のコードは使っているように見えます…。
そのままではありませんが。

**Comment by sakots** [comment]
ReactはFacebookやInstagram、VueはLINEなどで使われてます。

**Comment by sakots** [comment]
> futaba.phpのコードは入ってないと思いますが、POTI-boardのお絵かき関連のコードは使っているように見えます…。
> そのままではありませんが。

そうですわ

**Comment by satopian** [comment]
> Reactの注意点
> Reactを通さずDOMを操作するのは厳禁！
> これは、例えばjQueryを使ってDOMを追加／削除／変更することは厳禁！ということです。また、jQueryを通してイベントハンドラを設定することも厳禁です。これはReactが採用している「バーチャルDOM」という仕組みへの配慮です。

話はそれますが、これ、NEOやChickenPaintでDOMを作るのダメなのでは…。

**Comment by sakots** [comment]
気づかなかった！

**Comment by sakots** [comment]
VueでもjQueryのDOM操作とバッティングするかも。

**Comment by sakots** [comment]
解決。
